package models

type (
	Participants struct {
		Data []Participant `json:"data"`
	}

	Participant struct {
		Id         string                `json:"id"`
		Attributes ParticipantAttributes `json:"attributes"`
	}

	ParticipantAttributes struct {
		Name string `json:"name"`
	}
)

// type AutoGenerated struct {
// 	Data []struct {
// 		ID         string `json:"id"`
// 		Type       string `json:"type"`
// 		Attributes struct {
// 			Icon         interface{} `json:"icon"`
// 			Seed         int         `json:"seed"`
// 			Misc         interface{} `json:"misc"`
// 			Username     interface{} `json:"username"`
// 			FinalRank    interface{} `json:"final_rank"`
// 			GroupID      interface{} `json:"group_id"`
// 			TournamentID int         `json:"tournament_id"`
// 			Name         string      `json:"name"`
// 			Timestamps   struct {
// 				CreatedAt time.Time `json:"created_at"`
// 				UpdatedAt time.Time `json:"updated_at"`
// 			} `json:"timestamps"`
// 			States struct {
// 				Active bool `json:"active"`
// 			} `json:"states"`
// 		} `json:"attributes"`
// 		Relationships struct {
// 			Invitation struct {
// 				Data interface{} `json:"data"`
// 			} `json:"invitation"`
// 		} `json:"relationships"`
// 	} `json:"data"`
// 	Included []interface{} `json:"included"`
// 	Meta     struct {
// 		Count int `json:"count"`
// 	} `json:"meta"`
// 	Links struct {
// 		Self string `json:"self"`
// 		Next string `json:"next"`
// 		Prev string `json:"prev"`
// 	} `json:"links"`
// }
