package models

type (
	Tournaments struct {
		Data []Tournament `json:"data"`
	}

	Tournament struct {
		Id         string               `json:"id"`
		Attributes TournamentAttributes `json:"attributes"`
	}

	TournamentAttributes struct {
		Name     string `json:"name"`
		GameName string `json:"game_name"`
	}
)

// type AutoGenerated struct {
// 	Data []struct {
// 		ID         string `json:"id"`
// 		Type       string `json:"type"`
// 		Attributes struct {
// 			TournamentType          string      `json:"tournament_type"`
// 			URL                     string      `json:"url"`
// 			Name                    string      `json:"name"`
// 			State                   string      `json:"state"`
// 			Private                 bool        `json:"private"`
// 			Description             string      `json:"description"`
// 			GameName                string      `json:"game_name"`
// 			OauthApplicationID      interface{} `json:"oauth_application_id"`
// 			FullChallongeURL        string      `json:"full_challonge_url"`
// 			LiveImageURL            string      `json:"live_image_url"`
// 			SignUpURL               interface{} `json:"sign_up_url"`
// 			DecoratedTournamentType string      `json:"decorated_tournament_type"`
// 			StartsAt                interface{} `json:"starts_at"`
// 			Notifications           struct {
// 				UponMatchesOpen    bool `json:"upon_matches_open"`
// 				UponTournamentEnds bool `json:"upon_tournament_ends"`
// 			} `json:"notifications"`
// 			MatchOptions struct {
// 				ConsolationMatchesTargetRank interface{} `json:"consolation_matches_target_rank"`
// 				AcceptAttachments            bool        `json:"accept_attachments"`
// 			} `json:"match_options"`
// 			RegistrationOptions struct {
// 				OpenSignup      bool        `json:"open_signup"`
// 				SignupCap       interface{} `json:"signup_cap"`
// 				CheckInDuration interface{} `json:"check_in_duration"`
// 			} `json:"registration_options"`
// 			SeedingOptions struct {
// 				HideSeeds          bool `json:"hide_seeds"`
// 				SequentialPairings bool `json:"sequential_pairings"`
// 			} `json:"seeding_options"`
// 			DoubleEliminationOptions struct {
// 				SplitParticipants   bool        `json:"split_participants"`
// 				GrandFinalsModifier interface{} `json:"grand_finals_modifier"`
// 			} `json:"double_elimination_options"`
// 			StationOptions struct {
// 				AutoAssign                           bool `json:"auto_assign"`
// 				OnlyStartMatchesWithAssignedStations bool `json:"only_start_matches_with_assigned_stations"`
// 			} `json:"station_options"`
// 			GroupStageEnabled bool `json:"group_stage_enabled"`
// 			Timestamps        struct {
// 				StartsAt    interface{} `json:"starts_at"`
// 				StartedAt   time.Time   `json:"started_at"`
// 				CreatedAt   time.Time   `json:"created_at"`
// 				UpdatedAt   time.Time   `json:"updated_at"`
// 				CompletedAt interface{} `json:"completed_at"`
// 			} `json:"timestamps"`
// 		} `json:"attributes"`
// 		Relationships struct {
// 			Organizer struct {
// 				Data struct {
// 					ID   string `json:"id"`
// 					Type string `json:"type"`
// 				} `json:"data"`
// 			} `json:"organizer"`
// 			Community struct {
// 				Data interface{} `json:"data"`
// 			} `json:"community"`
// 			Matches struct {
// 				Links struct {
// 					Related string `json:"related"`
// 					Meta    struct {
// 						Count int `json:"count"`
// 					} `json:"meta"`
// 				} `json:"links"`
// 			} `json:"matches"`
// 			Participants struct {
// 				Links struct {
// 					Related string `json:"related"`
// 					Meta    struct {
// 						Count int `json:"count"`
// 					} `json:"meta"`
// 				} `json:"links"`
// 			} `json:"participants"`
// 			Stations struct {
// 				Links struct {
// 					Related string `json:"related"`
// 					Meta    struct {
// 						Count int `json:"count"`
// 					} `json:"meta"`
// 				} `json:"links"`
// 			} `json:"stations"`
// 			Series struct {
// 			} `json:"series"`
// 			Game struct {
// 				Data struct {
// 					ID   string `json:"id"`
// 					Type string `json:"type"`
// 				} `json:"data"`
// 			} `json:"game"`
// 			Petition struct {
// 			} `json:"petition"`
// 			LocalizedContents struct {
// 			} `json:"localized_contents"`
// 		} `json:"relationships"`
// 		Links struct {
// 			Self string `json:"self"`
// 		} `json:"links"`
// 	} `json:"data"`
// 	Included []struct {
// 		ID         string `json:"id"`
// 		Type       string `json:"type"`
// 		Attributes struct {
// 			Name     string   `json:"name"`
// 			Aliases  []string `json:"aliases"`
// 			Verified bool     `json:"verified"`
// 		} `json:"attributes"`
// 		Relationships struct {
// 			Competitions struct {
// 				Links struct {
// 					Related string `json:"related"`
// 					Meta    struct {
// 						Count int `json:"count"`
// 					} `json:"meta"`
// 				} `json:"links"`
// 			} `json:"competitions"`
// 		} `json:"relationships,omitempty"`
// 	} `json:"included"`
// 	Meta struct {
// 		Count int `json:"count"`
// 	} `json:"meta"`
// 	Links struct {
// 		Self string `json:"self"`
// 		Next string `json:"next"`
// 		Prev string `json:"prev"`
// 	} `json:"links"`
// }
